export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCHING_POST = 'FETCHING_POST';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATING_POST = 'UPDATING_POST';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETING_POST = 'DELETING_POST';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';