export const FETCH_CAT_POST_SUCCESS = 'FETCH_CAT_POST_SUCCESS';
export const FETCHING_CAT_POST = 'FETCHING_CAT_POST';
export const FETCH_CAT_POST_FAIL = 'FETCH_CAT_POST_FAIL';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';