export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCHING_COMMENT = 'FETCHING_COMMENT';
export const FETCH_COMMENT_FAIL = 'FETCH_COMMENT_FAIL';

export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATING_COMMENT = 'UPDATING_COMMENT';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETING_COMMENT = 'DELETING_COMMENT';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const COMMENT_COMMENT_SUCCESS = 'COMMENT_COMMENT_SUCCESS';
export const COMMENTING_COMMENT = 'COMMENTING_COMMENT';
export const COMMENT_COMMENT_FAIL = 'COMMENT_COMMENT_FAIL';